# Generated by Django 3.1.3 on 2020-11-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('fract', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'Fraction',
            },
        ),
    ]
